name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: esphome/build-action@v6
        with:
          yaml-file: esp32_4relay_test.yaml
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: "**/firmware*.bin"
